act_bug: false
act_num_samples: 100
activation_histograms: false
activation_mode: null
activation_seed: 42
alpha: 0.7
baseroot: D:\testings\Python\TestingPython\ModelFusion
batch_size_test: 1000
batch_size_train: 64
center_acts: false
choice: 0 2 4 6 8
cifar_style_data: false
ckpt_type: best
clip_gm: false
clip_max: 5
clip_min: 0
config_dir: D:\testings\Python\TestingPython\ModelFusion\configurations
config_file: null
correction: true
csv_dir: D:\testings\Python\TestingPython\ModelFusion\csv
dataset: mnist
debug: false
deprecated: null
deterministic: false
diff_init: false
disable_bias: true
dist_epochs: 60
dist_normalize: false
dump_final_models: false
dump_model: false
enable_dropout: false
ensemble_step: 0.5
eval_aligned: false
exact: false
exp_name: exp_2022-11-21_21-45-22_884543
geom_ensemble_type: wts
gpu_id: 0
gromov: false
gromov_loss: square_loss
ground_metric: euclidean
ground_metric_eff: false
ground_metric_normalize: log
handle_skips: false
importance: null
learning_rate: 0.01
load_models: ''
log_interval: 100
model_name: simplenet
momentum: 0.5
n_epochs: 1
no_random_trainloaders: false
normalize_acts: false
normalize_wts: false
not_squared: false
num_hidden_nodes: 400
num_hidden_nodes1: 400
num_hidden_nodes2: 200
num_hidden_nodes3: 100
num_hidden_nodes4: 50
num_models: 2
options_type: generic
partial_reshape: false
partition_dataloader: -1
partition_type: labels
past_correction: false
personal_class_idx: 9
personal_split_frac: 0.1
pool_acts: false
pool_relu: false
prediction_wts: false
prelu_acts: false
print_distances: false
proper_marginals: true
recheck_acc: false
recheck_cifar: false
reg: 0.01
reg_m: 0.001
reinit_trainloaders: false
result_dir: D:\testings\Python\TestingPython\ModelFusion\results
retrain: 0
retrain_avg_only: false
retrain_geometric_only: false
retrain_lr_decay: -1
retrain_lr_decay_epochs: null
retrain_lr_decay_factor: null
retrain_seed: -1
rootdir: D:\testings\Python\TestingPython\ModelFusion
same_model: -1
save_result_file: default.csv
second_model_name: null
sinkhorn_type: normal
skip_last_layer: false
skip_last_layer_type: average
skip_personal_idx: false
skip_retrain: -1
softmax_temperature: 1
standardize_acts: false
sweep_id: -1
sweep_name: null
temperature: 20
tensorboard: false
tensorboard_root: ./tensorboard
timestamp: 2022-11-21_21-45-22_884543
tmap_stats: false
to_download: false
transform_acts: false
unbalanced: false
update_acts: false
weight_stats: false
width_ratio: 1
